default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: hafiz
  password: 7764772

development:
  <<: *default
  database: internbox_development

test:
  <<: *default
  database: internbox_test
